Repository unicef/etools-partner-reporting-portal, pull requests merged in 2020-07, with the labels that each got.

#1515 [ch17412] Change label of card in overview to from "Financial Capacit…
  polymer_3/src_ts/elements/ip-reporting/risk-rating.ts
  polymer_3/src_ts/locales.ts
Labels: Frontend, ready

#1514 Remove unneeded packages to speed up docker build & npm install
  polymer_3/package-lock.json
  polymer_3/package.json
Labels: Frontend, ready

#1517 [ch21591] File upload issues
  polymer_3/src_ts/elements/ip-reporting/report-attachments.ts
Labels: Frontend

#1518 Add missing fields to PMPPartner serializer
  django_api/django_api/apps/partner/serializers.py
Labels: ready

#1519 Add filtering in exports at indicator reports level
  django_api/django_api/apps/unicef/exports/annex_c_excel.py
  django_api/django_api/apps/unicef/exports/programme_documents.py
  django_api/django_api/apps/unicef/exports/reportables.py
  django_api/django_api/apps/utils/mixins.py
Labels: ready

#1522 [ePD] Sync PRP users to eTools
  django_api/django_api/apps/partner/serializers.py
  django_api/django_api/apps/unicef/tests/test_views.py
  django_api/django_api/apps/unicef/urls.py
  django_api/django_api/apps/unicef/views.py
Labels: ready
