Repository unicef/etools-partner-reporting-portal, pull requests merged in 2020-06, with the labels that each got.

#1470 [ch20785] Special Report details: information about report is not dis…
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Labels: ready

#1471 [ch20792] Clicking on the report header link redirects user to Overview (not showing PD details)
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Labels: ready

#1473 [ch20789] Deleting Narrative for SR shows console error
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.ts
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Labels: ready

#1472 [ch20787] Special report: going back from download details brings con…
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
Labels: ready

#1474 [ch20415] Narrative save for Special Report issue
  polymer_3/src_ts/elements/ip-reporting/pd-report-info.ts
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
Labels: ready

#1476 [ch20363] Handle github security alerts on unicef-polymer
  polymer_3/package-lock.json
  polymer_3/package.json
Labels: ready

#1477 [ch20856] PRP role with no cluster triggers permission errors
  polymer_3/src_ts/elements/etools-prp-permissions.ts
Labels: ready

#1478 [ch20852] Add Activity as member dialog issues
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/editing-modal.ts
Labels: ready

#1480 [ch19886] Report refresh button, removes indicator location data from …
  polymer_3/src_ts/elements/refresh-report-modal.ts
  polymer_3/src_ts/locales.ts
Labels: ready

#1483 Add psea fields to partner detail serializer
  django_api/django_api/apps/partner/serializers.py
Labels: ready

#1482 Add admin button to sync and process PDs
  django_api/django_api/apps/unicef/admin.py
  django_api/django_api/apps/unicef/templates/admin/unicef/change_list.html
Labels: ready

#1481 [ch20785] Special Report details: information about report is not dis…
  polymer_3/src_ts/elements/ip-reporting/pd-details-reports.ts
Labels: ready

#1485 [ch17412] [PRP] Change label of card in overview to from "Financial C…
  polymer_3/src_ts/elements/ip-reporting/risk-rating.ts
  polymer_3/src_ts/locales.ts
Labels: ready

#1486 [ch20965] Prevent dialog closing on click outside.
  polymer_3/src_ts/elements/calculation-methods-demo-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/feedback-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/indicator-locations-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/message-imo-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/editing-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/editing-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/activities/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/activities/editing-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/disaggregations/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/editing-modal.ts
  polymer_3/src_ts/elements/cluster-reporting/send-back-modal.ts
  polymer_3/src_ts/elements/disaggregations/disaggregation-modal.ts
  polymer_3/src_ts/elements/error-modal.ts
  polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
  polymer_3/src_ts/elements/ip-reporting/pd-modal.ts
  polymer_3/src_ts/elements/pull-modal.ts
  polymer_3/src_ts/elements/refresh-report-modal.ts
  polymer_3/src_ts/elements/upload-button.ts
  polymer_3/src_ts/elements/user-profile/profile-dropdown.ts
  polymer_3/src_ts/mixins/overlay-helper-mixin.ts
  polymer_3/src_ts/pages/app/cluster-reporting/select-plan.ts
Labels: Frontend, ready

#1493 Update staging setting to not update CORS_ORIGIN_WHITELIST
  django_api/django_api/settings/staging.py
Labels: ready

#1492 Add bash to backend container
  .circleci/config.yml
  django_api/Dockerfile
Labels: ready

#1494 Allow Sentry to be configured in any environment
  django_api/django_api/settings/base.py
  django_api/django_api/settings/prod.py
Labels: ready

#1495 Add check ofn report refresh endpoint for future reports
  django_api/django_api/apps/indicator/tests/test_views.py
  django_api/django_api/apps/indicator/views.py
Labels: ready

#1498 Define disaggregation_reported_on as ListField so default value set
  django_api/django_api/apps/indicator/serializers.py
Labels: ready

#1454 Handle missing projects for PartnerActivity updates
  django_api/django_api/apps/partner/serializers.py
  django_api/django_api/apps/partner/tests/test_views.py
  django_api/django_api/apps/partner/views.py
Labels: On hold, ready

#1502 Fix parter activity update tests
  django_api/django_api/apps/partner/tests/test_views.py
Labels: ready

#1504 Programme document external
  django_api/django_api/apps/unicef/serializers.py
  django_api/django_api/apps/unicef/tests/test_tasks.py
Labels: ready

#1499 [ch21389] Console error at submitting Special Report
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Labels: Frontend, ready

#1442 [ch20405] Show 'buildDate' and 'revison' in package.json
  polymer_3/codefresh_polymer3.yml
  polymer_3/package.json
Labels: Frontend

#1506 Clean up more unique together validators in serializers
  django_api/django_api/apps/core/serializers.py
  django_api/django_api/apps/core/tests/factories.py
  django_api/django_api/apps/indicator/serializers.py
  django_api/django_api/apps/unicef/tests/test_tasks.py
Labels: ready

#1505 [ch21031] SEND A MESSAGE TO IMO dialog not opening
  polymer_3/src_ts/elements/cluster-reporting/cluster-report.ts
  polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
  polymer_3/src_ts/elements/cluster-reporting/message-imo-modal.ts
  polymer_3/src_ts/mixins/modal-mixin.ts
  polymer_3/src_ts/mixins/overlay-helper-mixin.ts
  polymer_3/src_ts/styles/modal-styles.ts
Labels: Frontend, ready

#1507 Remove allauth, does not look like it is being used.
  django_api/Pipfile
  django_api/Pipfile.lock
  django_api/django_api/settings/dev.py
  django_api/django_api/settings/prod.py
  django_api/django_api/settings/staging.py
Labels: ready

#1510 Correct cash transfer percentage value in exports
  django_api/django_api/apps/unicef/exports/programme_documents.py
Labels: ready

#1511 [ch21211] Changing the language makes the text bleed
  polymer_3/package-lock.json
  polymer_3/package.json
  polymer_3/src_ts/locales.ts
  polymer_3/src_ts/styles/table-styles.ts
Labels: Frontend, ready

#1512 [ch21538] Add Portuguese translations
  polymer_3/src_ts/locales.ts
Labels: Frontend, ready
