Repository unicef/etools-partner-reporting-portal, pull requests merged in 2020-10, with the labels that each got.

#1527 [ch22748] When a PD is ended the Partner does not see the Submit butt…
  polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Labels: Frontend, ready

#1530 [ch22077] Fix Add Response Plan
  polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
  polymer_3/src_ts/elements/ip-reporting/js/report-attachments-functions.ts
Labels: Frontend

#1531 Email validation
  django_api/django_api/apps/account/models.py
  django_api/django_api/apps/account/serializers.py
  django_api/django_api/apps/account/tests/test_models.py
  django_api/django_api/apps/account/tests/test_views.py
  django_api/django_api/apps/account/validators.py
  django_api/django_api/apps/unicef/models.py
  django_api/django_api/apps/unicef/serializers.py
  django_api/django_api/apps/unicef/tests/test_models.py
  django_api/django_api/apps/unicef/tests/test_tasks.py
Labels: ready

#1532 Update pmp link
  django_api/django_api/apps/unicef/models.py
Labels: ready

#1533 [ch23355] IP PRP: Getting spinning wheel of death when try to click on existing PD
  polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
Labels: Frontend, ready

#1529 Update pdf library to WeasyPrint
  .circleci/config.yml
  django_api/.isort.cfg
  django_api/Dockerfile-installed
  django_api/Makefile
  django_api/Pipfile
  django_api/Pipfile.lock
  django_api/django_api/apps/core/helpers.py
  django_api/django_api/apps/core/management/commands/_privates.py
  django_api/django_api/apps/core/models.py
  django_api/django_api/apps/core/tests/factories.py
  django_api/django_api/apps/indicator/serializers.py
  django_api/django_api/apps/indicator/utilities.py
  django_api/django_api/apps/partner/serializers.py
  django_api/django_api/apps/unicef/exports/annex_c_excel.py
  django_api/django_api/apps/unicef/exports/programme_documents.py
  django_api/django_api/apps/unicef/exports/progress_reports.py
  django_api/django_api/apps/unicef/exports/reportables.py
  django_api/django_api/apps/unicef/templates/programme_documents_pdf_export.css
  django_api/django_api/apps/unicef/templates/programme_documents_pdf_export.html
  django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.css
  django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.html
  django_api/django_api/apps/unicef/templates/progress_report_list_pdf_export.css
  django_api/django_api/apps/unicef/templates/progress_report_list_pdf_export.html
  django_api/django_api/apps/unicef/templates/report_annex_c_pdf.css
  django_api/django_api/apps/unicef/templates/report_annex_c_pdf.html
  django_api/django_api/apps/unicef/templates/reportable_list_pdf_export.css
  django_api/django_api/apps/unicef/templates/reportable_list_pdf_export.html
  django_api/django_api/apps/unicef/tests/test_views.py
  django_api/django_api/apps/unicef/utils.py
  django_api/django_api/apps/unicef/views.py
  django_api/django_api/apps/utils/emails.py
  django_api/django_api/apps/utils/mixins.py
  django_api/django_api/settings/base.py
  django_api/django_api/templates/custom_pdf_base.css
  django_api/tests/conftest.py
Labels: ready

#1535 [ch18564] IP-Reporting: List of Indicators and PDF Export Issues
  polymer_3/src_ts/elements/etools-prp-toolbar.ts
Labels: Frontend, ready

#1534 PDF export tweaks to table column widths
  django_api/Dockerfile-installed
  django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.css
  django_api/django_api/apps/unicef/templates/progress_report_list_pdf_export.css
  django_api/django_api/apps/unicef/tests/test_views.py
Labels: ready

#1536 Change font to ttf-opensans
  django_api/Dockerfile-installed
Labels: ready

#1537 Pass in correct queryset to EmailValidator on person serializer
  django_api/django_api/apps/unicef/serializers.py
Labels: ready

#1538 Add correct queryset for EmailValidator
  django_api/django_api/apps/unicef/serializers.py
Labels: ready
