Repository unicef/etools-partner-reporting-portal, pull requests merged in 2021-11, with the labels that each got.

#1639 [ch27329]Ci config for id-mgmt
  .circleci/config.yml
Labels: Ready

#1641 section fix
  django_api/etools_prp/apps/unicef/serializers.py
  django_api/etools_prp/apps/unicef/tasks.py
  django_api/etools_prp/apps/unicef/tests/test_tasks.py
Labels: Ready

#1607 sentry 4328
  django_api/etools_prp/apps/unicef/views.py
Labels: Ready, On hold

#1645 process PD task: fix section import
  django_api/etools_prp/apps/unicef/tasks.py
Labels: Ready

#1647 [ch26521] disaggregation default
  django_api/etools_prp/apps/indicator/migrations/0008_alter_indicatorlocationdata_disaggregation.py
  django_api/etools_prp/apps/indicator/models.py
  django_api/etools_prp/apps/unicef/tasks.py
Labels: Ready

#1644 [ch27348] tweak export permissions
  django_api/etools_prp/apps/core/permissions.py
  django_api/etools_prp/apps/unicef/views.py
Labels: Ready

#1646 [REFACTORING] Permission refactoring
  django_api/etools_prp/apps/core/permissions.py
  django_api/etools_prp/apps/indicator/views.py
  django_api/etools_prp/apps/unicef/permissions.py
  django_api/etools_prp/apps/unicef/views.py
Labels: enhancement, Ready
