Repository unicef/etools-partner-reporting-portal, pull requests merged in 2021-01, with the labels that each got.

#1550 [ch24557] moment.js is deprecated, time for an alternative
  polymer_3/.eslintrc.json
  polymer_3/index.html
  polymer_3/package.json
  polymer_3/polymer.json
  polymer_3/src_ts/app-shell.ts
  polymer_3/src_ts/elements/cluster-reporting/chip-date-of-report.ts
  polymer_3/src_ts/elements/etools-prp-chips.ts
  polymer_3/src_ts/elements/filters/date-filter/date-filter.ts
  polymer_3/src_ts/elements/ip-reporting/js/pd-details-overview-functions.ts
  polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
  polymer_3/src_ts/mixins/date-mixin.ts
  polymer_3/src_ts/mixins/utils-mixin.ts
  polymer_3/sw-precache-config.js
Labels: Frontend

#1551 [ch24557] moment.js is deprecated, time for an alternative
  polymer_3/package-lock.json
  polymer_3/package.json
Labels: Frontend, ready

#1553 [ch24672]Circleci setup
  .circleci/config.yml
Labels: ready

#1554 [ch24684] Refresh on PD details - the page remains in Loading state …
  polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
Labels: Frontend, ready
