Repository unicef/etools-partner-reporting-portal, pull requests merged in 2022-07, with the labels that each got.

#1773 [ch30530] Update logout url to `/social/unicef-logout/`
  frontend_ip/src_ts/endpoints.ts
Labels: Ready, Frontend

#1774 [ch30530] Update logout url to /social/unicef-logout/
  frontend_cluster/src_ts/endpoints.ts
Labels: Ready, Frontend

#1778 [ch30515] Calculation Methods label for Ratio Indicator is 'latest' instead of 'sum' [Reports]
  frontend_ip/src_ts/elements/ip-reporting/js/pd-details-calculation-methods-functions.ts
  frontend_ip/src_ts/elements/ip-reporting/pd-details-calculation-methods.ts
Labels: Ready

#1701 [ch28580] xls export incorrect values
  django_api/etools_prp/apps/unicef/exports/annex_c_excel.py
Labels: Ready

#1717 [ch28772][sentry-6395] Fix pdf export of progress report
  django_api/etools_prp/apps/indicator/tests/test_utilities.py
  django_api/etools_prp/apps/indicator/utilities.py
Labels: On hold

#1744 [ch29016] Added custom json Validator based on jsonschema lib
  django_api/Pipfile
  django_api/Pipfile.lock
  django_api/etools_prp/apps/core/validators.py
  django_api/etools_prp/apps/indicator/json_schemas.py
  django_api/etools_prp/apps/indicator/migrations/0009_auto_20220418_1714.py
  django_api/etools_prp/apps/indicator/models.py
  django_api/etools_prp/apps/indicator/serializers.py
  django_api/etools_prp/apps/indicator/tests/test_views.py
Labels: Ready

#1716 [ch28750] Added a 404 & 500 html page
  django_api/etools_prp/apps/core/templatetags/__init__.py
  django_api/etools_prp/apps/core/templatetags/prp.py
  django_api/etools_prp/config/settings.py
  django_api/etools_prp/config/urls.py
  django_api/etools_prp/static/images/unicefetools.svg
  django_api/etools_prp/templates/404.html
  django_api/etools_prp/templates/500.html
  django_api/etools_prp/templates/http_codes_base.html
Labels: Ready

#1784 [ch30530] Update logout url to /social/unicef-logout/
  frontend_cluster/src_ts/endpoints.ts
  frontend_ip/src_ts/endpoints.ts
Labels: Ready, Frontend

#1786 Json Validator schema fix: allow NULL value for v,d,c in indicators
  django_api/etools_prp/apps/indicator/json_schemas.py
  django_api/etools_prp/apps/indicator/tests/test_views.py
Labels: Ready

#1779 [ch30635]PD filter label tweak
  frontend_cluster/src_ts/locales.ts
  frontend_ip/src_ts/elements/filters/pd-filter/pd-dropdown-filter.ts
  frontend_ip/src_ts/locales.ts
Labels: Ready, Frontend

#1790 [HOTFix] for process_programme_document task on target/baseline string values instead of numeric
  django_api/etools_prp/apps/unicef/tasks.py
  django_api/etools_prp/apps/unicef/utils.py
Labels: Ready

#1789 [ch28580] Export xls progress report: fix ratio display type
  django_api/etools_prp/apps/unicef/exports/annex_c_excel.py
Labels: Ready

#1793 Add missing migration on indicators validator
  django_api/etools_prp/apps/indicator/migrations/0010_auto_20220725_1600.py
Labels: Ready
